### PR TITLE
added yarn.lock file

### PR DESCRIPTION
**Pull request by omerlh**
Minor, but important

### CODE REVIEW

**Comment by hackjutsu** [comment]
@omerlh 

Thank you for your PR. I'm not using yarn here, so I doubt how yarn.lock would help. Could shed some light on it?

**Comment by omerlh** [comment]
The main advantage (at least in my opinion) of yarn over npm is the yarn.lock. It is simmilar to npm`s shrinkwrap, but it has better integration with the tool. Meaning, any command in yarn update the lock file, where in npm you had to run additional command. So if you consider using yarn, this is a nice addition (with the better perfomance). Otherwise, it will be just outdated next time you will change something in the packages. 
Also, I noticed that this PR contains my personal profile, so if you are thinking of moving to yarn I can close this and open a PR from the dev branch in my fork.
BTW - thanks for this repo. I used it and it was very easy to setup.

**Comment by hackjutsu** [comment]
@omerlh 

Thanks for clarification:) Yes, I would love to merge the PR and switch to yarn if you can clean up the PR a little bit.

**Comment by omerlh** [comment]
Sure. I am closing this and open a new PR from the dev branch.

**Pull request closed without merging**
